Braniac/Braniac/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('', RedirectView.as_view(url='mainapp/')),  # переадресация на mainapp из пустой строки # возвращает 302
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
]

# если в режиме отладки раздаем статику
if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Braniac/authapp/urls.py
from django.urls import path
from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>", views.ProfileEditView.as_view(), name="profile_edit"),
]

Braniac/mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig
from django.views.decorators.cache import cache_page

app_name = MainappConfig.name

urlpatterns = [
    path('', cache_page(60 * 5)(views.MainPageView.as_view()), name='main_page'),  # кешируем страницу
    path('news/', views.NewsListView.as_view(), name='news'),
    path('news/create/', views.NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/detail', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:pk>/update', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/delete', views.NewsDeleteView.as_view(), name='news_delete'),
    path('courses/', views.CoursesPageView.as_view(), name='courses'),
    path('courses/<int:pk>', views.CourseDetailView.as_view(), name='courses_detail'),
    path('"course_feedback/', views.CourseFeedbackFormProcessView.as_view(), name='course_feedback'),
    path('log/', views.LogView.as_view(), name='log'),
    path('log/download', views.LogDownloadView.as_view(), name='log_download'),
    path('contacts/', views.ContactsPageView.as_view(), name='contacts'),
    path('doc_site/', views.DocSitePageView.as_view(), name='doc_site'),
    path('login/', views.LoginPageView.as_view(), name='login'),
]

Braniac/authapp/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.validators import EmailValidator
from django.db import models
from django.utils.translation import gettext_lazy as _  # транслитерация
from authapp.models_validators import AgeValidator

NULLABLE = {'blank': True, 'null': True}


class CustomUser(AbstractUser):
    username_validator = ASCIIUsernameValidator()  # валидатор - только ASCII символы
    age_validator = AgeValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text='Не больше 150 символов',
        validators=[username_validator],
        error_messages={'unique': _('User with that username already exists')})
    first_name = models.CharField(_('first name'), max_length=150, **NULLABLE)
    last_name = models.CharField(_('last name'), max_length=150, **NULLABLE)
    age = models.PositiveIntegerField(_('age'), validators=[age_validator], **NULLABLE)
    avatar = models.ImageField(upload_to='users', **NULLABLE)
    email = models.CharField(
        _('email address'),
        max_length=256,
        unique=True,
        error_messages={
            'unique': _('User with that email address already exists.')
        }
    )
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

Braniac/authapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from mainapp import models as mainapp_models
from django.contrib.auth.forms import UserCreationForm, UsernameField


class CustomUserCreationForm(
    UserCreationForm):  # форма регистрации пользователя(от модели), все данные указываются в классе Meta
    field_order = [  # порядок отображения на странице
        "username",
        "password1",
        "password2",
        "email",
        "first_name",
        "last_name",
        "age",
        "avatar",
    ]

    class Meta:
        model = get_user_model()  # возвращает модель пользователя для текущего проекта

        fields = (  # заполняемые поля, в порядке из таблицы
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}  # тип поля формы


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()

        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}

Braniac/authapp/views.py
import os

from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from authapp import models, forms


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'

    def form_valid(self, form):
        ret = super().form_valid(form)
        message = f'Login success <br>Hi, {self.request.user.get_username()}'  # TODO
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Something goes wrong:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, _('See you'))
        return super().dispatch(request, *args, **kwargs)


"""
Форма регистрации через POST:

class RegisterView(TemplateView):
    template_name = 'authapp/register.html'

    def post(self, request, *args, **kwargs):
        try:
            if request.POST.get('username') and request.POST.get('email') and request.POST.get('password1') == request.POST.get('password2'):
                # почему то при использовании all() ошибка all() takes exactly one argument, 3 given
                new_user = models.CustomUser.objects.create(
                    username=request.POST.get('username'),
                    first_name=request.POST.get('first_name'),
                    last_name=request.POST.get('last_name'),
                    age=request.POST.get('age') if request.POST.get('age') else 0,
                    avatar=request.FILES.get('avatar'),
                    email=request.POST.get('email'),
                )
                new_user.set_password(request.POST.get('password1'))
                new_user.save()
                messages.add_message(request, messages.INFO, _('Registration sucess'))
                return HttpResponseRedirect(reverse_lazy('authapp:login'))
        except Exception as exp:
            messages.add_message(
                request,
                messages.WARNING,
                mark_safe(f'Something goes wrong:<br>{exp}')
            )
            return HttpResponseRedirect(reverse_lazy('authapp:register'))
"""


class RegisterView(CreateView):
    # по умолчанию template_name будет равен customuser_form.html
    template_name = 'authapp/register.html'
    model = get_user_model()  # указываем модель пользователя для тек.проекта
    form_class = forms.CustomUserCreationForm  # указываем нашу форму
    success_url = reverse_lazy('authapp:login')  # при успехе, reverse_lazy наверное выдает полный путь


class ProfileEditView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = forms.CustomUserChangeForm

    def test_func(self):
        return True if self.request.user.pk == self.kwargs.get("pk") else False

    def get_success_url(self):
        return reverse_lazy("authapp:profile_edit", args=[self.request.user.pk])


"""
class ProfileEditView(LoginRequiredMixin, TemplateView):
    template_name = 'authapp/profile_edit.html'
    login_url = reverse_lazy('authapp:login')

    def post(self, request, *args, **kwargs):
        try:
            if request.POST.get("username"):
                request.user.username = request.POST.get("username")
            if request.POST.get("first_name"):
                request.user.first_name = request.POST.get("first_name")
            if request.POST.get("last_name"):
                request.user.last_name = request.POST.get("last_name")
            if request.POST.get("age"):
                request.user.age = request.POST.get("age")
            if request.POST.get("email"):
                request.user.email = request.POST.get("email")
            if request.FILES.get("avatar"):
                if request.user.avatar and os.path.exists(
                        request.user.avatar.path
                ):
                    os.remove(request.user.avatar.path)
                request.user.avatar = request.FILES.get("avatar")
            request.user.save()
            messages.add_message(request, messages.INFO, _("Saved!"))
        except Exception as exp:
            messages.add_message(
                request,
                messages.WARNING,
                mark_safe(f"Something goes worng:<br>{exp}"),
            )
        return HttpResponseRedirect(reverse_lazy("authapp:profile_edit"))
"""

Braniac/authapp/templates/authapp/login.html
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">
    <title>Welcome to Braniac!</title>
</head>
<body>

{% include 'includes/messages.html' %}

<div class="row justify-content-around align-items-center"
     style="height: 100vh; margin: 0px">
    <div class="text-center">
        <p>
            <a href="{% url 'mainapp:main_page' %}"><img
                    src="{% static 'img/logo.png' %}" alt=""></a>
        </p>
        <h2>Вход пользователя</h2>
        <form method="POST">

            {% csrf_token %}

            <p>
                <input type="text" name="username" autofocus=""
                       autocapitalize="none" autocomplete="username"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_username" placeholder="Username">
            </p>
            <p>
                <input type="password" name="password"
                       autocomplete="current-password"
                       class="textinput textInput form-control" required=""
                       id="id_password" placeholder="Password">
            </p>
            <p>
                <button type="submit"
                        class="btn btn-primary btn-block">Войти
                </button>
            </p>
        </form>
        <p>
        <div class="row justify-content-between">
            <div class="col">
                <a
                        href="{% url 'authapp:register'%}"><small>Регистрация</small></a>
            </div>
            <div class="col">
                <a href="#"><small>Забыли пароль?</small></a>
            </div>
        </div>
        </p>
        <h4>Вход через социальные сети</h4>
        <p>
        <div class="btn-group btn-block" role="group">
            <a class="btn btn-primary" href="#" role="button"><i
                    class="fab fa-vk"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i
                    class="fab fa-github"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i
                    class="fab fa-facebook"></i></a>
        </div>
        </p>
    </div>
</div>

<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>
<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>
<!-- Toasts -->
<script>
    $(document).ready(function () {
        {% if messages %}
    // Toasts
            $(".toast").toast({delay: 5000});
            $(".toast").toast("show");
        {% endif %}
    });
</script>
</body>
</html>

Braniac/authapp/templates/authapp/profile_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center my-2">
    <div class="col-lg-6">
        <h3>Редактирование профиля</h3>
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-5 col-lg-4">
                {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="" width="100%">
                {% else %}
                <img src="{{ MEDIA_URL }}avatar_default.svg" alt="" width="100%">
                {% endif %}
            </div>
        </div>
        <form method="post" class="mt-2" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="div_id_username" class="form-group"><label for="id_username"
                                                                class=" requiredField">
                Username<span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="username" maxlength="150"
                                     class="textinput textInput form-control" required id="id_username"
                                     value="{{ user.username }}"> <small id="hint_id_username"
                                                                         class="form-text text-muted">Required. 150
                    characters or fewer.
                    Letters, digits and @/./+/-/_ only.</small></div>
            </div>
            <div id="div_id_first_name" class="form-group"><label for="id_first_name"
                                                                  class="">
                First name
            </label>
                <div class=""><input type="text" name="first_name" maxlength="150"
                                     class="textinput textInput form-control" id="id_first_name"
                                     value="{{ user.first_name }}"></div>
            </div>
            <div id="div_id_last_name" class="form-group"><label for="id_last_name"
                                                                 class="">
                Last name
            </label>
                <div class=""><input type="text" name="last_name" maxlength="150"
                                     class="textinput textInput form-control" id="id_last_name"
                                     value="{{ user.last_name }}"></div>
            </div>
            <div id="div_id_age" class="form-group"><label for="id_age" class="">
                Age
            </label>
                <div class=""><input type="number" name="age" min="0"
                                     class="numberinput form-control" id="id_age" value="{{ user.age }}">
                </div>
            </div>
            <div id="div_id_avatar" class="form-group"><label for="id_avatar"
                                                              class="">
                Avatar
            </label>
                <div class=""><input type="file" name="avatar" accept="image/*"
                                     class="clearablefileinput form-control-file" id="id_avatar"></div>
            </div>
            <div id="div_id_email" class="form-group"><label for="id_email"
                                                             class=" requiredField">
                Email address<span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="email" maxlength="256"
                                     class="textinput textInput form-control" required="" id="id_email"
                                     value="{{ user.email }}">
                </div>
            </div>
            <button type=" submit"
                    class="btn btn-primary btn-block">Сохранить
            </button>
        </form>
    </div>
</div>
{% endblock content %}

Braniac/authapp/templates/authapp/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center my-2">
    <div class="col-lg-6">
        {% if user.is_anonymous %}
        <h3>Регистрация нового пользователя</h3>
        {% else %}
        <h3>Редактировать профиль</h3>
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-5 col-lg-4">
                {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="" width="100%">
                {% else %}
                <img src="{{ MEDIA_URL }}avatar_default.svg" alt="" width="100%">
                {% endif %}
            </div>
        </div>
        {% endif %}
        <form method="post" class="mt-2" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block">
                {% if user.is_anonymous %}
                Зарегистрироваться
                {% else %}
                Сохранить
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock content %}